# TODO:
# update eslint to flat config
# update all plugins
# tweak some TS config (void promises, no-throw-literal)
# add https://orm.drizzle.team/docs/eslint-plugin
# add https://tanstack.com/router/latest/docs/eslint/eslint-plugin-router
# add https://tanstack.com/query/latest/docs/eslint/eslint-plugin-query#eslint-plugin-query

env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - standard-with-typescript
  - prettier
plugins:
  - react
  - react-hooks
  - import
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
settings:
  import/resolver:
    typescript: true
  import/external-module-folders:
    - 'node_modules'
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
rules:
  space-before-function-paren: off
  react/no-unescaped-entities: off
  import/order:
    - 'error'
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - 'parent'
        - 'sibling'
        - 'index'
      alphabetize:
        order: 'asc'
      pathGroups:
        - pattern: 'react*'
          group: 'external'
          position: 'before'
        - pattern: '@**/*'
          group: 'external'
          position: 'after'
      pathGroupsExcludedImportTypes: []
  '@typescript-eslint/space-before-function-paren':
    - error
    - asyncArrow: always
      named: never
      anonymous: always
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/method-signature-style':
    - error
    - method
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/restrict-template-expressions': off
